#!/bin/bash



function create_build_directory() {
    mkdir -p _build
}



function copy_files() {
    cp docker_search/* _build/
    cp _libs/musgravite/musgravite.hpp _build/
    cp _tests/* _build
}



function main() {
    create_build_directory
    copy_files
}



main